namespace Goodtocode.AgentFramework.Infrastructure.AgentFramework.Embeddings;

/// <summary>
/// Abstraction for intent embedding storage and semantic similarity search.
/// Backend-agnostic: implementations can use SQL Server VECTOR, Azure AI Search, Cosmos DB vCore, etc.
/// Enables future migration without changing routing logic.
/// </summary>
public interface IIntentEmbeddingStore
{
    /// <summary>
    /// Stores a batch of embeddings for a specific intent.
    /// Typically called during seeding (Seed.StateOfYour) or app startup (IHostedService).
    /// Replaces any existing embeddings for the same intent (idempotent upsert).
    /// </summary>
    /// <param name="intentName">Intent name (e.g., "CreatePlaybook").</param>
    /// <param name="embeddings">Collection of embeddings to store.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task UpsertIntentEmbeddingsAsync(
        string intentName,
        IEnumerable<Embedding> embeddings,
        CancellationToken cancellationToken);

    /// <summary>
    /// Semantic search: finds embeddings similar to the query vector.
    /// Used by SemanticIntentClassifier to classify incoming user messages.
    /// </summary>
    /// <param name="queryVector">Embedding of the user's message (generated by IEmbeddingGenerator).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <param name="topK">Maximum number of results to return (default 5).</param>
    /// <param name="similarityThreshold">Minimum similarity score to accept (default 0.75).</param>
    /// <returns>
    /// List of EmbeddingMatch results sorted by similarity (descending).
    /// Empty if no matches above threshold.
    /// </returns>
    Task<IReadOnlyList<EmbeddingMatch>> SearchAsync(
        float[] queryVector,
        CancellationToken cancellationToken,
        int topK = 5,
        float similarityThreshold = 0.75f,
        IReadOnlySet<string>? eligibleIntentNames = null);

    /// <summary>
    /// Deletes all embeddings for a specific intent.
    /// Used during reseeding or when an intent is removed.
    /// </summary>
    /// <param name="intentName">Intent name to delete embeddings for.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task DeleteIntentEmbeddingsAsync(string intentName, CancellationToken cancellationToken);

    /// <summary>
    /// Health check: verifies embeddings are available and queryable.
    /// Returns true if store is ready; false if empty or unavailable.
    /// Used by IntentEmbeddingInitializationService (quick-start) to avoid regenerating.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task<bool> IsReadyAsync(CancellationToken cancellationToken);
}
