using Goodtocode.AgentFramework.Core.Application;
using Goodtocode.AgentFramework.Core.Application.Common.Exceptions;
using Goodtocode.AgentFramework.Infrastructure.AgentFramework.Options;
using Goodtocode.AgentFramework.Infrastructure.SqlServer.Persistence;
using Goodtocode.AgentFramework.Tests.Integration.Mocks;
using Microsoft.Agents.AI;

namespace Goodtocode.AgentFramework.Tests.Integration;

public abstract class TestBase : IDisposable
{
    public enum CommandResponseType
    {
        Successful,
        BadRequest,
        NotFound,
        Conflict,
        Error
    }

    internal string def = string.Empty;
    internal IDictionary<string, string[]> commandErrors =
        new ConcurrentDictionary<string, string[]>();
    internal Exception? exception;
    internal CommandResponseType responseType;
    internal ValidationResult validationResponse = new();

    internal AgentFrameworkContext context;

    internal IConfiguration configuration;
    internal IClaimsReader claimsReader;
    internal IRlsContext rlsContext;

    internal MockAIAgent agent = new();
    internal OpenAIOptions optionsOpenAi = new();

    protected IServiceProvider ServiceProvider { get; private set; } = default!;
    protected ISender Sender { get; private set; } = default!;

    public TestBase()
    {
        var executingType = Assembly.GetExecutingAssembly().GetTypes()
            .FirstOrDefault(x => x.Name == "AutoGeneratedProgram")
            ?? typeof(TestBase);
        configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.test.json", optional: true,
                reloadOnChange: true)
            .AddUserSecrets(executingType.Assembly, optional: true)
            .AddEnvironmentVariables()
            .Build();

        var services = new ServiceCollection();
        services.AddLogging();
        services.AddSingleton<IClaimsReader, MockClaimsReader>();
        services.AddSingleton<IRlsContext, UserContext>(provider =>
            UserContext.Create(provider.GetRequiredService<IClaimsReader>()));
        services.AddSingleton<AIAgent>(provider => agent);
        services.AddTransient(typeof(IPipelineBehavior<>),
            typeof(TestInjectUserContextBehavior<>));
        services.AddTransient(typeof(IPipelineBehavior<,>),
            typeof(TestInjectUserContextBehavior<,>));

        services.AddApplicationServices();

        services.AddDbContext<AgentFrameworkContext>(options =>
            options.UseInMemoryDatabase($"AgentFrameworkContext-{Guid.NewGuid()}")
                .UseLazyLoadingProxies());

        ConfigureServices(services);

        ServiceProvider = services.BuildServiceProvider();
        claimsReader = ServiceProvider.GetRequiredService<IClaimsReader>();
        rlsContext = ServiceProvider.GetRequiredService<IRlsContext>();
        context = ServiceProvider.GetRequiredService<AgentFrameworkContext>();
        Sender = ServiceProvider.GetRequiredService<ISender>();
    }

    internal CommandResponseType HandleAssignResponseType(Exception e)
    {
        exception = e;
        switch (e)
        {
            case CustomValidationException validationException:
                commandErrors = validationException.Errors;
                responseType = CommandResponseType.BadRequest;
                break;
            case CustomNotFoundException:
                responseType = CommandResponseType.NotFound;
                break;
            case CustomConflictException:
                responseType = CommandResponseType.Conflict;
                break;
            default:
                responseType = CommandResponseType.Error;
                break;
        }

        return responseType;
    }

    internal void HandleHasResponseType(string response)
    {
        switch (response)
        {
            case "Success":
                using (new AssertionScope())
                {
                    responseType.ShouldBe(CommandResponseType.Successful, BuildValidationErrorMessage());
                    exception.ShouldBeNull($"An exception was thrown: {exception?.Message}. Inner exception: {exception?.InnerException?.Message}");
                }
                break;
            case "BadRequest":
                responseType.ShouldBe(CommandResponseType.BadRequest, BuildValidationErrorMessage());
                break;
            case "NotFound":
                responseType.ShouldBe(CommandResponseType.NotFound);
                break;
            case "Error":
                responseType.ShouldBe(CommandResponseType.Error, BuildValidationErrorMessage());
                break;
        }
    }

    private string? BuildValidationErrorMessage()
    {
        if (responseType != CommandResponseType.BadRequest &&
            responseType != CommandResponseType.Error)
        {
            return null;
        }

        var errorMessages = new List<string>();

        if (responseType == CommandResponseType.BadRequest)
        {
            if (commandErrors.Any())
            {
                errorMessages.Add("Validation Errors from Command:");
                foreach (var error in commandErrors)
                {
                    var errorsForField = string.Join(", ", error.Value);
                    errorMessages.Add($"  - {error.Key}: {errorsForField}");
                }
            }

            if (validationResponse.Errors.Any())
            {
                errorMessages.Add("Validation Errors from Validator:");
                foreach (var error in validationResponse.Errors)
                {
                    errorMessages.Add($"  - {error.PropertyName}: {error.ErrorMessage}");
                }
            }
        }

        if (exception != null)
        {
            errorMessages.Add($"Exception Type: {exception.GetType().Name}");
            errorMessages.Add($"Exception Message: {exception.Message}");
            if (exception.InnerException != null)
            {
                errorMessages.Add($"Inner Exception: {exception.InnerException.Message}");
                errorMessages.Add($"Inner Exception StackTrace: {exception.InnerException.StackTrace}");
            }
            errorMessages.Add($"StackTrace: {exception.StackTrace}");
        }

        return errorMessages.Count != 0
            ? $"\n{string.Join("\n", errorMessages)}"
            : null;
    }

    internal void HandleExpectedValidationErrorsAssertions(string expectedErrors)
    {
        var def = this.def;

        if (string.IsNullOrWhiteSpace(expectedErrors))
        {
            return;
        }

        var expectedErrorsCollection = expectedErrors.Split(",");

        foreach (var field in expectedErrorsCollection)
        {
            var hasCommandValidatorErrors = validationResponse.Errors.Any(x => x.PropertyName == field.Trim());
            var hasCommandErrors = commandErrors.Any(x => x.Key == field.Trim());
            var hasErrorMatch = hasCommandErrors || hasCommandValidatorErrors;
            hasErrorMatch.ShouldBeTrue($"Expected a validation error for field '{field.Trim()}', but none was found.\nCommand Errors: [{string.Join(", ", commandErrors.Keys)}]\nValidator Errors: [{string.Join(", ", validationResponse.Errors.Select(e => e.PropertyName))}]");
        }
    }

    /// <summary>
    /// Override to register additional services into the shared <see cref="ServiceProvider"/>
    /// before it is built. Called by <see cref="TestBase"/> constructor after all base
    /// registrations are complete.
    /// </summary>
    protected virtual void ConfigureServices(IServiceCollection services) { }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (disposing)
        {
            context?.Dispose();
        }
    }
}