global using Goodtocode.AgentFramework.Core.Application.Abstractions;
global using Goodtocode.AgentFramework.Core.Application.Common.Auth;
global using Goodtocode.AgentFramework.Core.Application.Common.Exceptions;
global using Goodtocode.AgentFramework.Core.Application.Common.Mappings;
global using Goodtocode.AgentFramework.Core.Application.Common.Models;
global using Goodtocode.AgentFramework.Core.Application.Common.Pagination;
global using Goodtocode.AgentFramework.Core.Application.Common.Validators;
global using Goodtocode.Mediator;
global using Goodtocode.Validation;
global using Microsoft.EntityFrameworkCore;
global using ICollectStepTool = Goodtocode.Agents.Playbook.Steps.ICollectStepTool<Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewRequest, Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewEvidence>;
global using IEvaluateStepTool = Goodtocode.Agents.Playbook.Steps.IEvaluateStepTool<Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewEvidence, Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewFinding>;
global using IRecordStepTool = Goodtocode.Agents.Playbook.Steps.IRecordStepTool<Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewFinding, Goodtocode.AgentFramework.Core.Application.Playbooks.ReviewRecord>;
