global using Goodtocode.AgentFramework.Core.Application.Abstractions;
global using Goodtocode.AgentFramework.Core.Application.Common.Auth;
global using Goodtocode.AgentFramework.Core.Application.Common.Exceptions;
global using Goodtocode.AgentFramework.Core.Application.Common.Mappings;
global using Goodtocode.AgentFramework.Core.Application.Common.Pagination;
global using Goodtocode.AgentFramework.Core.Application.Common.Validators;
global using Goodtocode.Mediator;
global using Goodtocode.Validation;
global using Microsoft.EntityFrameworkCore;
