// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Goodtocode.AgentFramework.Tests.Integration.AgentFramework
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TokenIntentClassificationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "tokenIntentClassification"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "AgentFramework", "Token intent classification", "As a chat routing system\r\nI classify resilient natural-language variants determin" +
                "istically before semantic or LLM fallback", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "TokenIntentClassification.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("AgentFramework/TokenIntentClassification.feature.ndjson", 12);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 6, DisplayName="Token rules normalize aliases and punctuation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Token rules normalize aliases and punctuation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Token intent classification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tokenIntentClassification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("actor-by-name", "actor", "find,show;name,called", "", "Find these ACTORS, called Avery!", "actor-by-name", "0", null, DisplayName="Token rules normalize aliases and punctuation(actor-by-name,actor,find,show;name," +
            "called,,Find these ACTORS, called Avery!,actor-by-name,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("actor-by-name", "actor", "find,show;name,called", "message", "Show an actor named Avery", "actor-by-name", "1", null, DisplayName="Token rules normalize aliases and punctuation(actor-by-name,actor,find,show;name," +
            "called,message,Show an actor named Avery,actor-by-name,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("actor-by-name", "actor", "find,show;name,called", "", "Find this actor", "none", "2", null, DisplayName="Token rules normalize aliases and punctuation(actor-by-name,actor,find,show;name," +
            "called,,Find this actor,none,2)")]
        public async global::System.Threading.Tasks.Task TokenRulesNormalizeAliasesAndPunctuation(string intent, string allOf, string anyOfGroups, string noneOf, string message, string expected, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("intent", intent);
            argumentsOfScenario.Add("allOf", allOf);
            argumentsOfScenario.Add("anyOfGroups", anyOfGroups);
            argumentsOfScenario.Add("noneOf", noneOf);
            argumentsOfScenario.Add("message", message);
            argumentsOfScenario.Add("expected", expected);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Token rules normalize aliases and punctuation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync(string.Format("the token catalog contains intent \"{0}\" requiring all tokens \"{1}\" and any-of gro" +
                            "ups \"{2}\" with blockers \"{3}\"", intent, allOf, anyOfGroups, noneOf), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync(string.Format("I classify the standalone token message \"{0}\"", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.ThenAsync(string.Format("the token classified intent is \"{0}\"", expected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 17, DisplayName="Token rules extract values only after criteria match")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Token rules extract values only after criteria match")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Token intent classification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tokenIntentClassification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("actor-by-name", "actor", "find;name", "find this actor by name of", "Find this actor by name of Ada Lovelace", "actor-by-name", "name", "Ada Lovelace", "3", null, DisplayName="Token rules extract values only after criteria match(actor-by-name,actor,find;nam" +
            "e,find this actor by name of,Find this actor by name of Ada Lovelace,actor-by-na" +
            "me,name,Ada Lovelace,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("actor-by-name", "actor", "find;name", "find this actor by name of", "Find this actor without a subject", "none", "name", "", "4", null, DisplayName="Token rules extract values only after criteria match(actor-by-name,actor,find;nam" +
            "e,find this actor by name of,Find this actor without a subject,none,name,,4)")]
        public async global::System.Threading.Tasks.Task TokenRulesExtractValuesOnlyAfterCriteriaMatch(string intent, string allOf, string anyOfGroups, string prefix, string message, string expected, string captureName, string captureValue, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("intent", intent);
            argumentsOfScenario.Add("allOf", allOf);
            argumentsOfScenario.Add("anyOfGroups", anyOfGroups);
            argumentsOfScenario.Add("prefix", prefix);
            argumentsOfScenario.Add("message", message);
            argumentsOfScenario.Add("expected", expected);
            argumentsOfScenario.Add("captureName", captureName);
            argumentsOfScenario.Add("captureValue", captureValue);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Token rules extract values only after criteria match", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
 await testRunner.GivenAsync(string.Format("the token catalog contains intent \"{0}\" requiring all tokens \"{1}\" and any-of gro" +
                            "ups \"{2}\" with capture prefix \"{3}\"", intent, allOf, anyOfGroups, prefix), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
 await testRunner.WhenAsync(string.Format("I classify the standalone token message \"{0}\"", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
 await testRunner.ThenAsync(string.Format("the token classified intent is \"{0}\"", expected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
 await testRunner.AndAsync(string.Format("the token capture \"{0}\" is \"{1}\"", captureName, captureValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 28, DisplayName="More specific token rule wins")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("More specific token rule wins")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Token intent classification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tokenIntentClassification")]
        public async global::System.Threading.Tasks.Task MoreSpecificTokenRuleWins()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("More specific token rule wins", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
 await testRunner.GivenAsync("the token catalog contains a broad intent \"broad\" with all tokens \"actor\" and any" +
                        "-of groups \"show\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
 await testRunner.AndAsync("the token catalog contains a specific intent \"specific\" with all tokens \"actor;my" +
                        "\" and any-of groups \"show\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.WhenAsync("I classify the standalone token message \"show my actor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
 await testRunner.ThenAsync("the token classified intent is \"specific\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 34, DisplayName="Equal specificity token rules are ambiguous")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Equal specificity token rules are ambiguous")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Token intent classification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tokenIntentClassification")]
        public async global::System.Threading.Tasks.Task EqualSpecificityTokenRulesAreAmbiguous()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Equal specificity token rules are ambiguous", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
 await testRunner.GivenAsync("the token catalog contains a broad intent \"first\" with all tokens \"actor\" and any" +
                        "-of groups \"find\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
 await testRunner.AndAsync("the token catalog contains a specific intent \"second\" with all tokens \"actor\" and" +
                        " any-of groups \"find\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.WhenAsync("I classify the standalone token message \"find actor\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
 await testRunner.ThenAsync("the token classified intent is \"none\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(callerLineNumber: 40, DisplayName="Examples and follow-up rules remain deterministic fallbacks")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Examples and follow-up rules remain deterministic fallbacks")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Token intent classification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tokenIntentClassification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("list-chats", "list my chats", "", "Please list my chats", "", "list-chats", "level1", "7", null, DisplayName="Examples and follow-up rules remain deterministic fallbacks(list-chats,list my ch" +
            "ats,,Please list my chats,,list-chats,level1,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("follow-up", "", "which session?", "session from yesterday", "which session?", "follow-up", "level1", "8", null, DisplayName="Examples and follow-up rules remain deterministic fallbacks(follow-up,,which sess" +
            "ion?,session from yesterday,which session?,follow-up,level1,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("unknown", "known phrase", "", "unrelated request", "", "none", "none", "9", null, DisplayName="Examples and follow-up rules remain deterministic fallbacks(unknown,known phrase," +
            ",unrelated request,,none,none,9)")]
        public async global::System.Threading.Tasks.Task ExamplesAndFollow_UpRulesRemainDeterministicFallbacks(string intent, string example, string followUp, string message, string priorMessage, string expected, string level, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("intent", intent);
            argumentsOfScenario.Add("example", example);
            argumentsOfScenario.Add("followUp", followUp);
            argumentsOfScenario.Add("message", message);
            argumentsOfScenario.Add("priorMessage", priorMessage);
            argumentsOfScenario.Add("expected", expected);
            argumentsOfScenario.Add("level", level);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Examples and follow-up rules remain deterministic fallbacks", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
 await testRunner.GivenAsync(string.Format("the token catalog contains intent \"{0}\" with example \"{1}\" and follow-up \"{2}\"", intent, example, followUp), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
 await testRunner.WhenAsync(string.Format("I classify the token message \"{0}\" using prior user message \"{1}\"", message, priorMessage), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
 await testRunner.ThenAsync(string.Format("the token classified intent is \"{0}\"", expected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
 await testRunner.AndAsync(string.Format("the token classification level is \"{0}\"", level), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
